# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/CAN_controller/CAN_controller.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CAN_controller || ORIG_REF_NAME==CAN_controller} -quiet] -quiet

# IP: bd/CAN_controller/ip/CAN_controller_CAN_controller_0_0/CAN_controller_CAN_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CAN_controller_CAN_controller_0_0 || ORIG_REF_NAME==CAN_controller_CAN_controller_0_0} -quiet] -quiet

# XDC: c:/Users/croci/CAN/CAN.gen/sources_1/bd/CAN_controller/CAN_controller_ooc.xdc
