# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/croci/CAN/CAN.srcs/sources_1/ip/fifo_tx_83bit/fifo_tx_83bit.xci
# IP: The module: 'fifo_tx_83bit' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/croci/CAN/CAN.gen/sources_1/ip/fifo_tx_83bit/fifo_tx_83bit.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_tx_83bit'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/croci/CAN/CAN.gen/sources_1/ip/fifo_tx_83bit/fifo_tx_83bit_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_tx_83bit'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/croci/CAN/CAN.gen/sources_1/ip/fifo_tx_83bit/fifo_tx_83bit_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_tx_83bit'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/croci/CAN/CAN.srcs/sources_1/ip/fifo_tx_83bit/fifo_tx_83bit.xci
# IP: The module: 'fifo_tx_83bit' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/croci/CAN/CAN.gen/sources_1/ip/fifo_tx_83bit/fifo_tx_83bit.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_tx_83bit'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/croci/CAN/CAN.gen/sources_1/ip/fifo_tx_83bit/fifo_tx_83bit_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_tx_83bit'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/croci/CAN/CAN.gen/sources_1/ip/fifo_tx_83bit/fifo_tx_83bit_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_tx_83bit'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
